export const feedback = {
  id: 18,
  start_time: '2019-09-13T16:12:39.557183-04:00',
  end_time: '2019-09-13T16:29:30.493122-04:00',
  lessonrun_code: 21484,
  participant_set: [
    {
      id: 2,
      username: 'matt',
      first_name: 'Matt',
      last_name: 'Parson',
      email: 'matt@mybenji.com',
      verified_email: false,
      job_title: 'CEO',
      organization_name: 'Benji',
      orggroup_name: 'Sales',
      organization: 1,
      orggroup: 1,
      local_admin_permission: true,
      participant_permission: true,
    },
    {
      id: 8,
      username: 'khan',
      first_name: 'khan',
      last_name: '',
      email: '',
      verified_email: false,
      job_title: null,
      organization_name: null,
      orggroup_name: null,
      organization: null,
      orggroup: null,
      local_admin_permission: false,
      participant_permission: true,
    },
  ],
  host: {
    id: 2,
    username: 'matt',
    first_name: 'Matt',
    last_name: 'Parson',
    email: 'matt@mybenji.com',
    verified_email: false,
    job_title: 'CEO',
    organization_name: 'Benji',
    orggroup_name: 'Sales',
    organization: 1,
    orggroup: 1,
    local_admin_permission: true,
    participant_permission: true,
  },
  activity_results: [
    {
      id: 529,
      feedbackquestion_set: [
        {
          id: 92,
          feedbackparticipantanswer_set: [
            {
              user: {
                id: 2,
                username: 'matt',
                first_name: 'Matt',
                last_name: 'Parson',
                email: 'matt@mybenji.com',
                verified_email: false,
                job_title: 'CEO',
                organization_name: 'Benji',
                orggroup_name: 'Sales',
                organization: 1,
                orggroup: 1,
                local_admin_permission: true,
                participant_permission: true,
              },
              rating_answer: 3,
              text_answer: 'I didn"t find it much fun',
              feedbackquestion: 92,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 4,
              text_answer: 'I found it fun',
              feedbackquestion: 92,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 4,
              text_answer: 'I found it fun',
              feedbackquestion: 92,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 4,
              text_answer: 'I found it fun',
              feedbackquestion: 92,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 4,
              text_answer: 'I found it fun',
              feedbackquestion: 92,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 4,
              text_answer: 'I dont know man',
              feedbackquestion: 92,
            },
          ],
          average_rating: '3.50',
          question_type: 'rating_agreedisagree',
          question_text: 'What I learned in this session will improve my skills.',
          is_combo: true,
          combo_text: 'Why is that?',
          feedbackactivity: 529,
          pitchomaticactivity: null,
        },
        {
          id: 93,
          feedbackparticipantanswer_set: [
            {
              user: {
                id: 2,
                username: 'matt',
                first_name: 'Matt',
                last_name: 'Parson',
                email: 'matt@mybenji.com',
                verified_email: false,
                job_title: 'CEO',
                organization_name: 'Benji',
                orggroup_name: 'Sales',
                organization: 1,
                orggroup: 1,
                local_admin_permission: true,
                participant_permission: true,
              },
              rating_answer: 5,
              text_answer: '5',
              feedbackquestion: 93,
            },
            {
              user: {
                id: 8,
                username: 'khan',
                first_name: 'khan',
                last_name: '',
                email: '',
                verified_email: false,
                job_title: null,
                organization_name: null,
                orggroup_name: null,
                organization: null,
                orggroup: null,
                local_admin_permission: false,
                participant_permission: true,
              },
              rating_answer: 5,
              text_answer: '5',
              feedbackquestion: 93,
            },
          ],
          average_rating: '5.00',
          question_type: 'rating_agreedisagree',
          question_text: 'I found this session fun',
          is_combo: true,
          combo_text: null,
          feedbackactivity: 529,
          pitchomaticactivity: null,
        },
      ],
      titlecomponent: {
        title: 'Please leave some feedback for us!',
        title_image: 'emoji://memo',
        screen_instructions:
          "We'd really appreciate your feedback. Submit on your phone- it’ll only take a minute!",
        participant_instructions: "What did you think about today's lesson?",
      },
      activity_type: 'FeedbackActivity',
    },
  ],
};
